import Header from "./components/Header";
import "./globals.css";
import "bootstrap/dist/css/bootstrap.min.css";
import Herosection from "./components/Herosection";
export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body>
        <div className="text-center mt-12">
          <Header title="memory" />
        </div>
        <Herosection />
        {children}
      </body>
    </html>
  );
}
