import Header from "./components/Header";
import "./globals.css";
import "bootstrap/dist/css/bootstrap.min.css";
import Herosection from "./components/Herosection";
import BioSection from './components/BioSection'
import GalTributeSection from './components/GalTributeSection'
import SendMessageForm from './components/SendMessageForm'
import Footer from './components/Footer'
export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body>
        <div className="text-center mt-12">
          <Header title="memory" />
        </div>
        <Herosection />
        <BioSection />
        <GalTributeSection />
        {children}
        <SendMessageForm />
        <Footer />
      </body>
    </html>
  );
}
