import "./globals.css";
import "bootstrap/dist/css/bootstrap.min.css";
import Footer from "./components/Footer";
import NavRest from './components/NavRest'
export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body>
        {children}
        <Footer />
      </body>
    </html>
  );
}
